option(ZYDIS_BUILD_EXAMPLES "" OFF)
option(ZYDIS_BUILD_TOOLS "" OFF)

option(ZYDIS_FEATURE_AVX512 "" ON)
option(ZYDIS_FEATURE_KNC "" ON)
option(ZYDIS_FEATURE_DECODER "" ON)
option(ZYDIS_FEATURE_FORMATTER "" OFF)

add_subdirectory(deps/zydis)

if(PROJECT_IS_TOP_LEVEL)
  set_target_properties(Zydis PROPERTIES FOLDER "Dependencies")
  set_target_properties(Zycore PROPERTIES FOLDER "Dependencies")

  mark_as_advanced(
    ZYAN_DEV_MODE
    ZYAN_FORCE_ASSERTS
    ZYAN_NO_LIBC
    ZYAN_WHOLE_PROGRAM_OPTIMIZATION
    ZYCORE_BUILD_EXAMPLES
    ZYCORE_BUILD_SHARED_LIB
    ZYCORE_BUILD_TESTS
    ZYDIS_BUILD_EXAMPLES
    ZYDIS_BUILD_SHARED_LIB
    ZYDIS_BUILD_TOOLS
    ZYDIS_FEATURE_AVX512
    ZYDIS_FEATURE_KNC
    ZYDIS_FEATURE_DECODER
    ZYDIS_FEATURE_FORMATTER
    ZYDIS_FUZZ_AFL_FAST
    ZYDIS_LIBFUZZER
    ZYDIS_MINIMAL_MODE
    ZYDIS_ZYCORE_PATH
  )
endif()
