name: Build
on: [ push, pull_request ]

jobs:
  build:
    name: Build (${{ matrix.platform }}, ${{ matrix.config }}, C++${{ matrix.standard }})
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [ Win32, x64 ]
        config: [ Debug, Release, MinSizeRel, RelWithDebInfo ]
        standard: [ 14, 17, 20, 23 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake `
            -A ${{ matrix.platform }} `
            -DCMAKE_CXX_STANDARD=${{ matrix.standard }} `
            -DRENHOOK_BUILD_TESTS=YES `
            -DRENHOOK_EXTRA_WARNINGS=YES `
            -DRENHOOK_TREAT_WARNINGS_AS_ERRORS=YES `
            ${{ github.workspace }}

      - name: Build
        working-directory: build
        run: |
          cmake `
            --build . `
            --config ${{ matrix.config }}

      - name: Test
        working-directory: build/tests/${{ matrix.config }}
        run: ./Tests.exe
